name: menu_happy_cream
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'







dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: 
  cloud_firestore: 
  firebase_auth: 
  firebase_storage:
  google_sign_in: 


  
  
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  image_picker: ^1.1.2
  gap:
  fluttertoast: 
  swipeable_button_view:
  page_transition:
  device_preview: ^1.2.0
  url_launcher: ^6.0.20
  badges: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true


  assets:
    - assets/icon.png
    - assets/icon/icon.png
    - assets/icon/google.png
    - assets/icon/facebook.png
    - assets/icon/granja.png
    - assets/icon/valla.png
    - assets/icon/vaca.png
    - assets/icon/carne.png
    - assets/icon/granjero.png
    - assets/icon/granjeroI.png
    - assets/icon/1st.png
    - assets/icon/2st.png
    - assets/icon/3st.png
    - assets/vaca.jpg
    - assets/Producto.jpg

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
