// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiBpburgDBmiohyuy-TZzK_DBO92xSq-M',
    appId: '1:989118869902:web:91de3de62c9421642034df',
    messagingSenderId: '989118869902',
    projectId: 'happy-cream',
    authDomain: 'happy-cream.firebaseapp.com',
    storageBucket: 'happy-cream.appspot.com',
    measurementId: 'G-JL5TN28PFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1RjL0OQclCDSLFoPRimfpA-zG-NGkSg',
    appId: '1:989118869902:android:90fd2f140a6123e82034df',
    messagingSenderId: '989118869902',
    projectId: 'happy-cream',
    storageBucket: 'happy-cream.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2qn4SidY0_k2QaysBdlSvHrqgL4fo2Hc',
    appId: '1:989118869902:ios:6eb7650496cfb4272034df',
    messagingSenderId: '989118869902',
    projectId: 'happy-cream',
    storageBucket: 'happy-cream.appspot.com',
    iosBundleId: 'com.example.happycream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2qn4SidY0_k2QaysBdlSvHrqgL4fo2Hc',
    appId: '1:989118869902:ios:6eb7650496cfb4272034df',
    messagingSenderId: '989118869902',
    projectId: 'happy-cream',
    storageBucket: 'happy-cream.appspot.com',
    iosBundleId: 'com.example.happycream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiBpburgDBmiohyuy-TZzK_DBO92xSq-M',
    appId: '1:989118869902:web:0cafd3ced82bf1c42034df',
    messagingSenderId: '989118869902',
    projectId: 'happy-cream',
    authDomain: 'happy-cream.firebaseapp.com',
    storageBucket: 'happy-cream.appspot.com',
    measurementId: 'G-1BCLBB7PTN',
  );
}
